todo/urls.py
from django.contrib import admin
from django.urls import path,include
from todo_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('',include('todo_app.urls')),
    path('logout/',views.user_logout,name="logout"),
]

todo_app/urls.py
from django.urls import path,include
from todo_app import views

app_name = 'todo_app'

urlpatterns = [
    
    path('register/',views.register,name="register"),
    path('user_login/',views.user_login,name="user_login"),
    path('add_note/',views.add_note,name="add_note"),
    path('view_note/',views.view_note,name="view_note"),
    path('delete_todo/<int:todo_id>/',views.delete_item,name="delete_item"),

]

todo_app/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()
import datetime

# Create your models here.

class todo_item(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    description = models.TextField(max_length=250)

    def __str__(self):
        return self.user.username

todo_app/forms.py
from django import forms
from django.contrib.auth import get_user_model
User = get_user_model()
from todo_app.models import todo_item

class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User

        fields = ('first_name','last_name','username','email','password')

class todoForm(forms.ModelForm):

    class Meta():
        model = todo_item

        fields = ('title','description')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'myfieldclass'}),
            'description': forms.Textarea(attrs={'class': 'myfieldclass1'})
        }

todo_app/views.py
from django.shortcuts import render
from todo_app.forms import UserForm, todoForm
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from todo_app.models import todo_item,User
# Create your views here.

def index(request):

    return render(request, 'todo_app/index.html')

def register(request):

    registered = False
    
    if request.method=="POST":

        user_form = UserForm(data=request.POST)

        if user_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered=True
        else:
            return HttpResponse("Invalid details")

    else:
        user_form = UserForm()

    return render(request,'todo_app/registration.html',{
                            'registered':registered,
                            'user_form':user_form})

def user_login(request):

    if( request.method=="POST" ):
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if( user ):
            if(user.is_active):
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
                

            else:
                return HttpResponse("Account Not Active")
        else:
            print('Someone tried to login and failed!!')
            print("Username : {} and Password : {}".format(username,password))
            return HttpResponse("Invalid credentials")

    else:
        return render(request,'todo_app/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def add_note(request):

    if request.method=="POST":
        todo_form = todoForm(data=request.POST)

        if todo_form.is_valid():
            todo_item.objects.create(user=request.user, title=request.POST.get('title'), description=request.POST.get('description'))
        else:
            return HttpResponse("Invalid details")
        
        
    todo_form = todoForm()
    return render(request,'todo_app/add_note.html',{'todo_form':todo_form})

@login_required
def view_note(request):
    currentUser_id = request.user.id
    usr = User.objects.get(pk=currentUser_id)
    objs = todo_item.objects.filter(user=usr)
    list_isThere = True
    
    if(len(objs)==0):
        list_isThere=False
        objs = {}
        heading = "Hey, There!"
        message = "You have nothing in your notes. Go To \'Add a note\' to add notes"
        objs[heading] = message

    return render(request,'todo_app/view_note.html',{'todo_list':objs,'list_isThere':list_isThere})

@login_required
def delete_item(request, todo_id):

    itm_to_delete = todo_item.objects.get(id=todo_id)
    itm_to_delete.delete()
    return HttpResponseRedirect(reverse('todo_app:view_note'))

templates/todo_app/add_note.html
{% extends "todo_app/base.html" %}
{% load static %}

{% block title %}
Add a note
{% endblock %}

{% block start_body %}

<div class="jumbotron">

    <h1>Add the Note!!</h1>
    <h3>Fill in the details:</h3>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        {{ todo_form.as_table }} 

        <input type="submit" name="" value="Create">
    </form>

</div>

{% endblock %}

templates/todo_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %}My Web app{% endblock %} </title>
    <link rel="stylesheet" type="text/css" href="{% static '/css/mystyles.CSS' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    {% block head %}
    {% endblock %}
</head>
<body style="background-color:coral;">
    
    <ul>
        <li><a href="{% url 'index' %}">Home</a></li>

        {% if user.is_authenticated %}
            <li><a href="{% url 'todo_app:add_note' %}">Add a note</a></li>
            <li><a href="{% url 'todo_app:view_note' %}">Pending Notes</a></li>
            <li style="float:right"><a href="{% url 'logout' %}"> Logout </a></li>
        {% else %}
            <li><a href="{% url 'todo_app:register' %}">Register</a></li>
            <li style="float:right"><a href="{% url 'todo_app:user_login' %}"> Login </a></li>    
        {% endif %}
    </ul>

    <div class="container">
        {% block start_body %}

        {% endblock %}
    </div>

</body>
</html>

templates/todo_app/index.html
{% extends "todo_app/base.html" %}

{% block title %}
Home
{% endblock %}

{% block start_body %}

{% if user.is_authenticated %}

<div class="jumbotron">
    <h2> This is your homepage! </h2>
    <h3> Go to 'Add a note' to create a new note. </h3>
    <h3> Go to 'Pending' to see existing note. </h3>
</div>

{% else %}

<div class="jumbotron">
    <h1> Welcome to the application! </h1>
    <h4> Made using Django </h4>
    <h3> You can organize your todo lists using this Web app </h3>
</div>

{% endif %}

{% endblock %}

templates/todo_app/login.html
{% extends "todo_app/base.html" %}
{% load static %}

{% block title %}
Login
{% endblock %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block start_body %}

<div class="jumbotron">
    <h1> Please Login </h1>
    
    <form action="{% url 'todo_app:user_login' %}" method="POST">
        
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">
        
        <label for="password">Password:</label>
        <input type="password" name="password">
        <br>

        {% csrf_token %}
        
        <input type="submit" name="" value="Login">
    </form>

</div>

{% endblock %}

templates/todo_app/registration.html
{% extends "todo_app/base.html" %}

{% block title %}
Registration
{% endblock %}

{% block start_body %}

<div class="jumbotron">
    
    {% if registered %}
        <h1> Thank You for registering at our site.</h1>
        <h3> Please Login and start using our app.</h3>
    {% else %}
        <h1>Register Here!!</h1>
        <h3>Please fill out the form:</h3>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            <input type="submit" name="" value="Register">
        </form>

    {% endif %}

</div>

{% endblock %}

templates/todo_app/view_note.html
{% extends "todo_app/base.html" %}
{% load static %}
{% block title %}
Notes
{% endblock %}

{% block start_body %}

{% if list_isThere %}
{% for itm in todo_list %}
    <div class="jumbotron">
        <h2> <strong> {{ itm.title }} </strong> </h2>
        <p>{{ itm.description }}</p>

        <form action="/delete_todo/{{itm.id}}" method='GET'>
        <button class="button" type='submit'>Delete</button>
        </form>
        
    </div>
{% endfor %}
{% else %}
{% for titl,des in todo_list.items %}
    <div class="jumbotron">
        <h2> <strong> {{ titl }} </strong> </h2>
        <p>{{ des }}</p>
    </div>
{% endfor %}
{% endif %}

{% endblock %}